sudo: true
language: node_js
dist: trusty
notifications:
  email: false
node_js:
  - '11'
before_install:
  - npm i -g npm@^6
script:
  - run-p test lint format
after_failure: cat npm-debug.log
after_success:
  - semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
